export const PATHS = {
  LOGIN:        '/login',
  HOME:         '/',
  PRODUCTS:     '/products',
  STOCK_SHEET:  '/products/:id/fiche-stock',
  LOW_STOCK:    '/low-stock',
  ENTRIES:      '/entries',
  REMOVALS:     '/removals',
  REMOVAL_FORM: '/removal-form',
  SALES:        '/sales',
  REPORTS:          '/reports',
  BILAN_MATERIEL:   '/reports/materiel',
  BILAN_FINANCIER:  '/reports/financier',
  SESSION:      '/session',
  EXPENSES:     '/expenses',
  USERS:        '/users',
  PROFILE:      '/profile',
  SETTINGS:     '/settings',
  BOUTIQUES:    '/boutiques',
  ADMIN_HOME:   '/admin',
} as const;
