# Generated by Django 5.2.7 on 2025-10-25 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='products.product')),
            ],
            options={
                'db_table': 'entries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Removal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(choices=[('vente', 'Vente'), ('don', 'Don'), ('perte', 'Perte')], max_length=20)),
                ('removal_ref', models.CharField(max_length=30, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removals_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removals_invoiced', to='billing.invoice')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removals', to='products.product')),
            ],
            options={
                'db_table': 'removals',
            },
        ),
        migrations.CreateModel(
            name='RemovalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('removal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.removal')),
            ],
            options={
                'db_table': 'removal_items',
            },
        ),
    ]
