# Generated by Django 5.2.7 on 2025-10-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Removal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(max_length=20)),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'removals',
                'managed': False,
            },
        ),
    ]
