# Generated by Django 5.2.7 on 2025-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_issued',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('payee', 'Payée'), ('en_attente', 'En attente'), ('annulee', 'Annulée')], default='payee', max_length=20),
            preserve_default=False,
        ),
    ]
