# image Node officielle légère
FROM node:20-alpine            

WORKDIR /app

COPY package*.json ./

# installe les dépendances (plus fiable que npm install)
RUN npm ci                     

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
# --host 0.0.0.0 = accessible depuis l'extérieur du conteneur