# Generated by Django 5.2.7 on 2025-10-30 02:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='products.product')),
            ],
            options={
                'db_table': 'entries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_register', models.DateTimeField(blank=True, editable=False)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.product')),
            ],
            options={
                'verbose_name': 'historical entry',
                'verbose_name_plural': 'historical entrys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRemoval',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_register', models.DateTimeField(blank=True, editable=False)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(choices=[('vente', 'Vente'), ('don', 'Don'), ('perte', 'Perte')], max_length=20)),
                ('removal_ref', models.CharField(db_index=True, max_length=30)),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice_total_amount', models.IntegerField(blank=True, null=True)),
                ('invoice_status', models.CharField(choices=[('payee', 'Payée'), ('en_attente', 'En attente'), ('annulee', 'Annulée')], max_length=20)),
                ('invoice_date_created', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical removal',
                'verbose_name_plural': 'historical removals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Removal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(choices=[('vente', 'Vente'), ('don', 'Don'), ('perte', 'Perte')], max_length=20)),
                ('removal_ref', models.CharField(max_length=30, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice_total_amount', models.IntegerField(blank=True, null=True)),
                ('invoice_status', models.CharField(choices=[('payee', 'Payée'), ('en_attente', 'En attente'), ('annulee', 'Annulée')], max_length=20)),
                ('invoice_date_created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'removals',
            },
        ),
        migrations.CreateModel(
            name='RemovalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('removal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.removal')),
            ],
            options={
                'db_table': 'removal_items',
            },
        ),
    ]
