# Generated by Django 5.2.7 on 2026-05-28 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_boutique_historicaluser_role_user_role_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='accounts.boutique'),
        ),
        migrations.AddField(
            model_name='historicalentry',
            name='boutique',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.boutique'),
        ),
        migrations.AddField(
            model_name='historicalremoval',
            name='boutique',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.boutique'),
        ),
        migrations.AddField(
            model_name='removal',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removals', to='accounts.boutique'),
        ),
    ]
