# Generated by Django 5.2.7 on 2026-05-29 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_entry_boutique_historicalentry_boutique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalremoval',
            name='invoice_status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('annulee', 'Annulée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='removal',
            name='invoice_status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('annulee', 'Annulée')], max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('carte', 'Carte Bancaire')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('removal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stock.removal')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['date'],
            },
        ),
    ]
