# Generated by Django 5.2.7 on 2026-06-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_removal_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='removalitem',
            name='purchase_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalremoval',
            name='invoice_status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='removal',
            name='invoice_status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée')], max_length=20),
        ),
    ]
