# Generated by Django 5.2.7 on 2026-06-14 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_boutique_logo'),
        ('products', '0004_product_products_boutiqu_29eb94_idx'),
        ('stock', '0007_add_purchase_price_snapshot_to_removal_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['boutique', 'date_register'], name='entries_boutiqu_cb9d32_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['product', 'date_register'], name='entries_product_bd7dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['boutique', 'date_register'], name='expenses_boutiqu_d90c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['removal', 'date'], name='payments_removal_01c64e_idx'),
        ),
        migrations.AddIndex(
            model_name='removal',
            index=models.Index(fields=['boutique', 'date_register'], name='removals_boutiqu_84964b_idx'),
        ),
        migrations.AddIndex(
            model_name='removal',
            index=models.Index(fields=['boutique', 'destination'], name='removals_boutiqu_ccd2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='removal',
            index=models.Index(fields=['boutique', 'destination', 'date_register'], name='removals_boutiqu_95ca27_idx'),
        ),
    ]
