# on part d'une image Python officielle
FROM python:3.12-slim          

# les logs s'affichent immédiatement
ENV PYTHONUNBUFFERED=1         

# le dossier de travail dans le conteneur
WORKDIR /app                   

# on installe d'abord les dépendances système nécessaires à psycopg2
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
 && rm -rf /var/lib/apt/lists/*

# on copie et installe les requirements Python
COPY requirements/base.txt requirements/base.txt
COPY requirements/dev.txt  requirements/dev.txt
RUN pip install -r requirements/dev.txt

# on copie tout le code
COPY . .                       

# on ouvre le port 8000
EXPOSE 8000                    