# Generated by Django 5.2.7 on 2026-05-28 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Boutique',
                'db_table': 'boutiques',
            },
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Propriétaire'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employé')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Propriétaire'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employé')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='boutique',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.boutique'),
        ),
        migrations.AddField(
            model_name='user',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.boutique'),
        ),
    ]
