# Generated by Django 5.2.7 on 2026-05-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_boutique_address_boutique_email_boutique_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='boutique_logos/'),
        ),
    ]
