# Generated by Django 5.2.7 on 2025-10-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('electronique', 'Électronique'), ('meublier', 'Meublier'), ('informatique', 'Informatique')], max_length=20)),
                ('product_ref', models.CharField(max_length=20, unique=True)),
                ('stock', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('alert', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
