# Generated by Django 5.2.7 on 2026-06-14 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_boutique_logo'),
        ('products', '0003_product_boutique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['boutique', 'stock'], name='products_boutiqu_29eb94_idx'),
        ),
    ]
